import { describe, it, expect } from 'vitest';
import {
  generateTotpSecret,
  base32Decode,
  base32Encode,
  hotp,
  totp,
  verifyTotp,
  otpauthUri,
} from '@/lib/services/totp';

// RFC 4226 Appendix D test vectors: ASCII secret "12345678901234567890",
// base32-encoded as "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ".
const RFC4226_SECRET_B32 = 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ';
const RFC4226_CODES = [
  '755224',
  '287082',
  '359152',
  '969429',
  '338314',
  '254676',
  '287922',
  '162583',
  '399871',
  '520489',
];

describe('base32', () => {
  it('round-trips arbitrary bytes', () => {
    const buf = Buffer.from('12345678901234567890', 'ascii');
    expect(base32Encode(buf)).toBe(RFC4226_SECRET_B32);
    expect(base32Decode(RFC4226_SECRET_B32).equals(buf)).toBe(true);
  });

  it('round-trips random bytes generated by generateTotpSecret', () => {
    const secret = generateTotpSecret();
    expect(secret).toMatch(/^[A-Z2-7]+$/);
    const decoded = base32Decode(secret);
    expect(decoded.length).toBe(20);
    expect(base32Encode(decoded)).toBe(secret);
  });
});

describe('hotp (RFC 4226 test vectors)', () => {
  const secretBytes = base32Decode(RFC4226_SECRET_B32);

  RFC4226_CODES.forEach((code, counter) => {
    it(`counter ${counter} -> ${code}`, () => {
      expect(hotp(secretBytes, counter)).toBe(code);
    });
  });
});

describe('totp', () => {
  it('produces a 6-digit code deterministic on time', () => {
    const secret = generateTotpSecret();
    const at = Date.UTC(2026, 0, 1, 0, 0, 0);
    const a = totp(secret, at);
    const b = totp(secret, at);
    expect(a).toBe(b);
    expect(a).toMatch(/^\d{6}$/);
  });

  it('matches RFC 4226 counter-based codes at the corresponding time step', () => {
    // period = 30s, so counter N corresponds to atMs = N * 30_000.
    RFC4226_CODES.forEach((code, counter) => {
      expect(totp(RFC4226_SECRET_B32, counter * 30_000)).toBe(code);
    });
  });
});

describe('verifyTotp', () => {
  it('accepts a freshly generated code', () => {
    const secret = generateTotpSecret();
    const now = Date.now();
    const code = totp(secret, now);
    expect(verifyTotp(secret, code, now)).toBe(true);
  });

  it('rejects a wrong code', () => {
    const secret = generateTotpSecret();
    const now = Date.now();
    const code = totp(secret, now);
    const wrong = code === '000000' ? '111111' : '000000';
    expect(verifyTotp(secret, wrong, now)).toBe(false);
  });

  it('tolerates +-1 step clock skew', () => {
    const secret = generateTotpSecret();
    const now = 1_700_000_000_000;
    const prevStepCode = totp(secret, now - 30_000);
    const nextStepCode = totp(secret, now + 30_000);
    expect(verifyTotp(secret, prevStepCode, now)).toBe(true);
    expect(verifyTotp(secret, nextStepCode, now)).toBe(true);
  });

  it('rejects codes outside the +-1 step window', () => {
    const secret = generateTotpSecret();
    const now = 1_700_000_000_000;
    const farCode = totp(secret, now - 90_000);
    expect(verifyTotp(secret, farCode, now)).toBe(false);
  });
});

describe('otpauthUri', () => {
  it('formats a standard otpauth:// TOTP URI', () => {
    const uri = otpauthUri('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 'alice');
    expect(uri).toBe(
      'otpauth://totp/GEM-ZT:alice?secret=GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ&issuer=GEM-ZT&algorithm=SHA1&digits=6&period=30',
    );
  });

  it('accepts a custom issuer', () => {
    const uri = otpauthUri('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 'bob', 'MyApp');
    expect(uri).toContain('otpauth://totp/MyApp:bob?');
    expect(uri).toContain('issuer=MyApp');
  });
});
